export const logoFeedbackConst = {
  id: 0,
  rowVersion: '',
  location: '',
  ipAddress: '192.168.1.1',
  macAddress: '00-00-00-00-00-00',
  customerId: 0,
  customerLogoId: 0,
  adminId: 0,
  longDescription: '',
  logoImageName: '',
  isApproved: true,
  approvedDate: new Date(),
  logoType: 0,
  isAdmin: 0,
  logoSize: '',
  embroideryColor: '',
  parentId: 0,
};
